name: "🐛 Bug report"
description: Report something that isn't working
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below so I can reproduce it.

  - type: input
    id: version
    attributes:
      label: App / Project version
      description: What version are you using? (If you don't know, say "unknown")
      placeholder: "e.g. v1.2.3"
    validations:
      required: false

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Tell me what you expected, and what actually happened.
      placeholder: "Expected: ...\nActual: ..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps so I can reproduce the bug.
      placeholder: |
        1. Go to...
        2. Click...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Screenshots / Logs (optional)
      description: Paste logs here or drag-and-drop screenshots into the issue.
      placeholder: "Attach files or paste logs..."
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Other
    validations:
      required: false

